# docker-compose.yml
version: "2.4"

volumes:
  db_data:

services:
    boilerplate_mysql:
      container_name: boilerplate_mysql
      build:
        context: ./db/
        dockerfile: Dockerfile
      restart: always
      ports:
        - '3306:3306'
      volumes:
        - db_data:/var/lib/mysql

    boilerplate_service:
      container_name: boilerplate_service

      # Make sure healthcheck is present in container image for following dependecies
      depends_on:
        boilerplate_mysql:
          condition: service_healthy

      build:
        context: .
        dockerfile: Dockerfile
        target: prod
        args:
          - NPM_TOKEN=$NPM_TOKEN

      volumes:
        - .:/app:delegated

      ports:
        - 8080:8080

      environment:
        - ENVIRONMENT=DEVELOPMENT
        - MICROSERVICE_NAME=BOILERPLATE
        - MICROSERVICE_IP=0.0.0.0
        - APP_HOST=0.0.0.0
        - APP_PORT=8080
        - SWAGGER_PORT=8080
        - MYSQL_HOST=boilerplate_mysql
        - MYSQL_USERNAME=user
        - MYSQL_PASSWORD=secret
        - MYSQL_DB_NAME=notes
